theme: jekyll-theme-cayman
files_root: https://github.com/vrw-GH/vrw-GH/raw/main/
file_1: resume/cv_vw-en.pdf
file_2: certificates/Victor_Wright-Recommendation_letter.pdf
file_3: certificates/WBS-certificate_FS_Web_&_App_Dev.pdf
file_4: certificates/Front-End_Web_Development_E-Certificate.pdf
file_5: certificates/certificate_of_completion_c++.pdf
file_6: certificates/JFA_Emp-Certificate.pdf
