theme: jekyll-theme-time-machine
plugins:
  - jekyll-seo-tag


- name: Deploy to GitHub Pages
  uses: JamesIves/github-pages-deploy-action@v4.3.3

- name: Git Version
  uses: codacy/git-version@2.4.0
